### ISSUE TITLE
Error: undeclared identifier: 'ID' in stable and latest

### ISSUE THREAD

**Issue by Dev1lroot** [bung87/crowngui#3]
Installing crowngui@#head
   Building crowngui/crowngui.exe using c backend
C:\Users\dev1lroot\AppData\Local\Temp\nimble_9460\githubcom_bung87crowngui_#head\src\crownguipkg\webview.nim(22, 11) Error: undeclared identifier: 'ID'
       Tip: 49 messages have been suppressed, use --verbose to show them.
     Error: Build failed for package: crowngui
        ... Execution failed with exit code 1
        ... Command: I:\WindowsLibrary\Terminal\nim-1.4.6\bin\nim.exe c --colors:on --noNimblePath -d:release -d:NimblePkgVersion=0.2.7 --path:C:\Users\dev1lroot\.nimble\pkgs\regex-0.19.0 --path:C:\Users\dev1lroot\.nimble\pkgs\unicodedb-0.9.0 --path:C:\Users\dev1lroot\.nimble\pkgs\xlsx-0.4.5 --path:C:\Users\dev1lroot\.nimble\pkgs\zip-0.3.1 --path:C:\Users\dev1lroot\.nimble\pkgs\static_server-2.2.0 --path:C:\Users\dev1lroot\.nimble\pkgs\finder-0.2.0 --path:C:\Users\dev1lroot\.nimble\pkgs\zippy-0.5.6 --path:C:\Users\dev1lroot\.nimble\pkgs\jsonschema-0.2.1 --path:C:\Users\dev1lroot\.nimble\pkgs\ast_pattern_matching-1.0.0 --path:C:\Users\dev1lroot\.nimble\pkgs\objc_runtime-0.1.0 --path:C:\Users\dev1lroot\.nimble\pkgs\darwin-#master --path:C:\Users\dev1lroot\.nimble\pkgs\darwin-#master --hints:off -o:C:\Users\dev1lroot\AppData\Local\Temp\nimble_9460\githubcom_bung87crowngui_#head\crowngui.exe C:\Users\dev1lroot\AppData\Local\Temp\nimble_9460\githubcom_bung87crowngui_#head\src\crowngui.nim

**Comment by bung87** [comment]
I just push fix to v0.2.8 and master, `crowngui` is under development, I mainly focus on macOS.
