### ISSUE TITLE
Using webview2.nim 

### ISSUE THREAD

**Issue by harrier77** [bung87/crowngui#6]
I want to use the code in [webview2.nim](https://github.com/bung87/crowngui/blob/devel/src/crowngui/platforms/win/webview2.nim) without the crowngui app to learn something about the internals of webview, it seems it should be possible because there is this code at line 250:
```
when isMainModule:
  SetCurrentProcessExplicitAppUserModelID("webview2 app")
  var v = newWebView()
  assert v.webview_init() == 0

  v.run
```
but there is no newWebView() proc which can be called. 
How can I  write a newWebView() that starts the app?
I tried to add this at line 252: import ../../webview.nim
and I can compile, but it fails to run with this error:  
ERROR:window_impl.cc(121)] Failed to unregister class Chrome_WidgetWin_0. Error = 0

**Comment by bung87** [comment]
I haven't touched this project for a while, for your fist question, import modules as you need explicitly. the second seems cause by destroy window before exiting webview, that might can be ignored. as error code is `0`

**Comment by harrier77** [comment]
Thank you very much for quick answer. I tried  with this and I can finally get a webview window:
```
import webview
var v=newWebView()
discard v.webview_init()
v.run
```
On the other hand, using assert v.webview_init() == 0 as in the webview2.nim code causes an error like this:
Error: unhandled exception: prova.nim(5, 1) `v.webview_init() == 0`  [AssertionDefect]

**Comment by harrier77** [comment]
How can I add a custom button to the webview window I can get with the code above? (It should be useful to have  a "home" button with which redirect the browser to a starting page. )

**Comment by bung87** [comment]
that's more specific to windows gui development, webview2 official repo has such a sample, you can check it there.

**Comment by harrier77** [comment]
Thanks for your answer, in the meantime I made some improvement in my skills and actually I can now write some C lines that add a custom toolbar to a webview2 window; after that it is relatively easy to convert C to nim. 
Here is the code for a toolbar inside your webview2 window in nim:

 ```nim
 var tbab1,tbab2,tbab3:TTBADDBITMAP
  type tbbtipo = array[0..3,TBBUTTON]
  var tbb:tbbtipo
  
  var miatoolb=CreateWindowW(
    TOOLBARCLASSNAME, 
    NULL, 
    WS_CHILD or WS_VISIBLE or TBSTYLE_FLAT, 
    0, 0, 0, 0, 
    w.priv.windowHandle, 
    cast[HMENU](NULL),
    g_hInstance,  
    cast[LPVOID](w))

SendMessage(miatoolb, TB_BUTTONSTRUCTSIZE, cast[WPARAM](sizeof(TBBUTTON)), 0)
  SendMessage(miatoolb, TB_SETBITMAPSIZE, cast[WPARAM](0), cast[LPARAM](MAKELONG(32, 32)))
  const
    IDB_BACK = 1003
    IDB_FOR = 1004
    IDB_HOME = 1005
    MIO_COMANDO = 11
  ##Add Bitmaps
  tbab1.hInst  = g_hInstance
  tbab1.nID    = IDB_BACK
  SendMessage(miatoolb, TB_ADDBITMAP, cast[WPARAM](1), cast[LPARAM](&tbab1))
  
  tbab2.hInst  = g_hInstance
  tbab2.nID    = IDB_HOME
  SendMessage(miatoolb, TB_ADDBITMAP, cast[WPARAM](1), cast[LPARAM](&tbab2))

  tbab3.hInst  = g_hInstance
  tbab3.nID    = IDB_FOR
  SendMessage(miatoolb, TB_ADDBITMAP, cast[WPARAM](1), cast[LPARAM](&tbab3));

  #ZeroMemory(cast[PVOID](NULL),sizeof(tbb))
  tbb[0].iBitmap    = 0 ##The index of the bitmap on toolbar bitmap collection
  tbb[0].idCommand  = MIO_COMANDO
  tbb[0].fsState    = TBSTATE_ENABLED
  tbb[0].fsStyle    = TBSTYLE_BUTTON
  
  tbb[1].iBitmap    = 1 
  tbb[1].idCommand  = 0
  tbb[1].fsState    = TBSTATE_ENABLED;
  tbb[1].fsStyle    = TBSTYLE_BUTTON
  ##tbb[1].iString    = SendMessage(hWndToolBar, TB_ADDSTRING, 0, (LPARAM)TEXT(""));

  tbb[2].iBitmap    = 2 
  tbb[2].idCommand  = 0
  tbb[2].fsState    = TBSTATE_ENABLED 
  tbb[2].fsStyle    = TBSTYLE_BUTTON 
  ##tbb[1].iString    = SendMessage(hWndToolBar, TB_ADDSTRING, 0, (LPARAM)TEXT(""));
  
  SendMessage(miatoolb, TB_ADDBUTTONS, 3, cast[LPARAM](&tbb))
```

**Comment by harrier77** [comment]
Hello again, I started a new project and I can not get the return value of a nim proc when I call it from javascript. 
For example, I can bind the javascript api.carica_dati() to the nim proc in this way:
```
proc due (webview: Webview; data:string):string =
       return "myvar"

v.bindProcs("api"):
        proc carica_dati(data:string) =  carica_dati(v,data)
```
and when I call api.carica_dati() inside the webview page I can see that the corresponding nim proc runs.
But I need to read the return value of nim proc in javascript and at now I can not get it. 
Can you give me a simple example of a binded nim proc wich returns a string?

**Comment by bung87** [comment]
it's not supported. I might take a look at https://github.com/webui-dev/nim-webui see how it is implemented.

**Comment by harrier77** [comment]
Hello I have just fixed that old problem. 
Now I have a new repo with your code and my fix here: https://github.com/harrier77/webview2_nim

**Comment by bung87** [comment]
looks like code reformated, hard to review, if you would like to contribute, you can create clean pr to this repo

**Comment by harrier77** [comment]
I am an amateur, I made the fix using opencode and to send a PR I should fork entire crowngui project which very different from mine. 
I asked copilot on github and this is what it says about the critical fix in my code on javascript return:

```
## Bug
JavaScript functions with return values fail to resolve their promises 
because the initialization logic incorrectly handles HTML content vs URLs.

## Root Cause
The current logic checks `entryType` but uses the same `w.url` field for both 
HTML and URL navigation, causing embedded HTML to not be loaded properly. This 
breaks the DOM initialization and prevents JavaScript callbacks from executing.

## Fix
Change the logic to check if HTML content exists (`w.initHtml.len > 0`) and 
use the appropriate navigation method:
- If HTML content exists: use `NavigateToString(&T(w.initHtml))`  
- Otherwise: use `Navigate(T(w.url))`

## Impact
- Fixes promise resolution for JavaScript functions with return values
- Fixes `window._nimCallbacks[id]()` callback mechanism
- Properly initializes the WebView2 DOM for embedded HTML

## Files Changed
- `src/crowngui/platforms/win/webview2/controllers.nim` (lines 68-71)

## Before
```nim
if w.entryType == EntryType.html:
  discard w.priv.view.NavigateToString(T(w.url))
else:
  discard w.priv.view.Navigate(T(w.url))
```

**Comment by bung87** [comment]
that's a misuse problem
